---
abstract: 'uses the DateTime roles for testing'
author:
  - 'Harold Frayman <harold.frayman@theguardian.com>'
build_requires:
  Test::More: '0'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.031, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Halx-Role-DateTime
requires:
  Halx::DateFormat: '0'
  Halx::Type::DateTime: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Getopt: '0'
  MooseX::Role::Parameterized: '0'
  namespace::autoclean: '0'
  perl: '5.016'
  warnings: '0'
version: 0.0.2
x_generated_by_perl: v5.38.2
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
